;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="STC.Damage>Shield.Shield",NewTagName="STC.Damage.Shield")
+GameplayTagRedirects=(OldTagName="STC.Damage>Shield",NewTagName="STC.Damage")
+GameplayTagList=(Tag="Attack.Melee.Sword",DevComment="")
+GameplayTagList=(Tag="Attack.Projectile.Watermelon",DevComment="")
+GameplayTagList=(Tag="Bond.Test",DevComment="")
+GameplayTagList=(Tag="Bond.Test.2",DevComment="")
+GameplayTagList=(Tag="Bond.Test.4",DevComment="")
+GameplayTagList=(Tag="Enemy.Land.Name",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Attack.Projectile.Watermelon",DevComment="")
+GameplayTagList=(Tag="Item.Active.Buffs.Shield",DevComment="")
+GameplayTagList=(Tag="Item.Active.Melee.Sword",DevComment="")
+GameplayTagList=(Tag="Item.Active.Projectile.Strawberry",DevComment="")
+GameplayTagList=(Tag="Item.Active.Projectile.Watermelon",DevComment="")
+GameplayTagList=(Tag="Item.Passive.HappyLamp",DevComment="")
+GameplayTagList=(Tag="Item.Passive.Reflection",DevComment="")
+GameplayTagList=(Tag="Item.Passive.Skull",DevComment="")
+GameplayTagList=(Tag="STC.Damage.Health",DevComment="")
+GameplayTagList=(Tag="STC.Damage.Shield",DevComment="")
+GameplayTagList=(Tag="Store.GoldUpdate",DevComment="")

