;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Attack.Melee.Sword",DevComment="")
+GameplayTagList=(Tag="Enemy.Land.Name",DevComment="")
+GameplayTagList=(Tag="Item.Active.Melee.Sword",DevComment="")
+GameplayTagList=(Tag="Item.Active.Projectile.Strawberry",DevComment="")
+GameplayTagList=(Tag="Item.Passive.HappyLamp",DevComment="")
+GameplayTagList=(Tag="Item.Passive.Skull",DevComment="")
+GameplayTagList=(Tag="Store.GoldUpdate",DevComment="")

